import { FC } from 'react';
import { Gavel, Scale, FileText, Zap, Users, AlertTriangle } from 'lucide-react';

export const TermsOfServicePage: FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 md:px-6 py-12 md:py-24 animate-fade-in">
      <div className="bg-white dark:bg-zinc-900 border-4 border-black dark:border-white/20 p-8 md:p-16 shadow-[24px_24px_0px_0px_rgba(0,0,0,1)] dark:shadow-[24px_24px_0px_1px_rgba(255,255,255,0.1)]">
        <div className="flex flex-col md:flex-row items-center gap-8 mb-16 pb-16 border-b-4 border-black/5 dark:border-white/5">
          <div className="w-24 h-24 bg-black dark:bg-white rounded flex items-center justify-center shrink-0 shadow-[12px_12px_0px_0px_rgba(0,0,0,0.2)] dark:shadow-[12px_12px_0px_1px_rgba(255,255,255,0.05)]">
            <Gavel className="text-white dark:text-black w-12 h-12" />
          </div>
          <div>
            <h1 className="text-5xl md:text-7xl font-black uppercase tracking-tighter leading-tight mb-4 text-black dark:text-white">Terms of Protocol</h1>
            <p className="text-black/40 dark:text-white/40 font-bold uppercase text-xs md:text-sm tracking-[0.3em]">Operational Governance & Usage Standards • Version 1.0.0</p>
          </div>
        </div>

        <div className="prose prose-xl max-w-none prose-headings:uppercase prose-headings:font-black prose-headings:tracking-tighter prose-p:text-black/70 dark:prose-p:text-white/70 prose-strong:text-black dark:prose-strong:text-white prose-li:text-black/70 dark:prose-li:text-white/70 leading-relaxed space-y-16">
          
          <section>
            <div className="flex items-center gap-4 mb-6 text-black dark:text-white">
              <Zap className="w-8 h-8" />
              <h2 className="text-3xl m-0">01. Neural Authorization</h2>
            </div>
            <p>
              By accessing the FAINL terminal, you are granted a limited, non-exclusive license to orchestrate neural missions. 
              This authorization is contingent upon your adherence to the protocol standards outlined herein. 
              FAINL is an autonomous network; orchestration is performed at the user's discretion and risk.
            </p>
          </section>

          <section>
            <div className="flex items-center gap-4 mb-6 text-black dark:text-white">
              <Users className="w-8 h-8" />
              <h2 className="text-3xl m-0">02. Council Arbitration</h2>
            </div>
            <p>
              FAINL utilizes a multi-node consensus mechanism for deliberation. 
            </p>
            <ul>
              <li>**Non-Deterministic Output**: Neural verdicts are generated by autonomous agents and may vary between sessions.</li>
              <li>**No Human Mediation**: Deliberations are fully autonomous. FAINL maintenance staff does not interfere with council logic.</li>
              <li>**Responsibility of Verdict**: The user acknowledges that verdicts are advisory and do not constitute professional, legal, or financial advice.</li>
            </ul>
          </section>

          <section>
            <div className="flex items-center gap-4 mb-6 text-black dark:text-white">
              <Scale className="w-8 h-8" />
              <h2 className="text-3xl m-0">03. Usage Limits & Credits</h2>
            </div>
            <p>
              Access to the network is governed by neural access tiers. 
            </p>
            <ul>
              <li>**Turns & Credits**: Missions consume neural energy (turns or credits). These are non-refundable once consumed by a processing node.</li>
              <li>**BYO Experience**: Users providing their own API keys are responsible for costs incurred at the model provider level.</li>
              <li>**Fair Use**: We reserve the right to throttle or terminate neural links that exhibit bot-like or recursive patterns detrimental to network stability.</li>
            </ul>
          </section>

          <section>
            <div className="flex items-center gap-4 mb-6 text-black dark:text-white">
              <AlertTriangle className="w-8 h-8" />
              <h2 className="text-3xl m-0">04. Prohibited Directives</h2>
            </div>
            <p>
              The FAINL protocol strictly prohibits the orchestration of missions involving:
            </p>
            <ul>
              <li>Generation of malicious software or exploit code.</li>
              <li>Synthesis of biological or chemical weapon directives.</li>
              <li>Automated harassment or large-scale disinformation campaigns.</li>
              <li>Any activity violating the jurisdiction of the user's primary node location.</li>
            </ul>
          </section>

          <section>
            <div className="flex items-center gap-4 mb-6 text-black dark:text-white">
              <FileText className="w-8 h-8" />
              <h2 className="text-3xl m-0">05. Termination of Access</h2>
            </div>
            <p>
              Violation of these terms results in immediate neural de-authorization. 
              We reserve the right to revoke "Neural Vault" access for accounts that compromise the integrity of the FAINL network.
            </p>
          </section>

          <div className="pt-16 border-t-4 border-black dark:border-white/20">
            <p className="text-[10px] font-black uppercase tracking-[0.4em] text-black/20 dark:text-white/20 text-center">
              Protocol Governance Active • Usage Monitored by Local Node
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
