import { FC } from 'react';
import { Gavel, Scale, FileText, Zap, Users, AlertTriangle } from 'lucide-react';

export const TermsOfServicePage: FC = () => {
  return (
    <div className="max-w-3xl mx-auto px-4 md:px-6 py-10 md:py-16 animate-fade-in-up">

      {/* Header */}
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-zinc-100 dark:bg-zinc-1000/10 border border-zinc-200 dark:border-white/10 text-zinc-800 dark:text-zinc-200 text-xs font-semibold mb-4">
          <Gavel className="w-3.5 h-3.5" />
          Terms of Service
        </div>
        <h1 className="text-2xl md:text-3xl font-bold text-zinc-900 dark:text-zinc-100 tracking-tight mb-3">
          Terms of Service
        </h1>
        <p className="max-w-sm mx-auto text-sm text-zinc-400 dark:text-zinc-500 leading-relaxed">
          By using FAINL, you agree to these terms. Please read them carefully.
        </p>
        <p className="mt-3 text-xs text-zinc-400 dark:text-zinc-600 font-medium">Version 1.0.0 · Effective immediately</p>
      </div>

      {/* Sections */}
      <div className="space-y-4">

        <div className="glass-card card-shadow rounded-2xl p-6 md:p-7 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-400/15 to-transparent" />
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-xl bg-zinc-100 dark:bg-zinc-1000/10 flex items-center justify-center shrink-0">
              <Zap className="w-4 h-4 text-zinc-800 dark:text-zinc-200" />
            </div>
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">Acceptable Use</h2>
          </div>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed">
            By accessing FAINL, you are granted a limited, non-exclusive license to use the service for personal and professional analysis. This license requires adherence to the terms below. FAINL is a tool — all outputs are advisory and the responsibility for how they are used remains with you.
          </p>
        </div>

        <div className="glass-card card-shadow rounded-2xl p-6 md:p-7 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-400/15 to-transparent" />
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-xl bg-zinc-100 dark:bg-zinc-1000/10 flex items-center justify-center shrink-0">
              <Users className="w-4 h-4 text-zinc-800 dark:text-zinc-200" />
            </div>
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">AI-Generated Content</h2>
          </div>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed mb-3">
            FAINL uses multiple AI models to generate responses. Please note:
          </p>
          <ul className="space-y-2 text-sm text-zinc-500 dark:text-zinc-400">
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">Non-deterministic output:</strong> Responses are generated by AI and may vary between sessions.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">Not professional advice:</strong> AI verdicts do not constitute legal, financial, medical, or any other form of professional advice.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">No interference:</strong> FAINL staff does not review or interfere with individual AI responses.</span>
            </li>
          </ul>
        </div>

        <div className="glass-card card-shadow rounded-2xl p-6 md:p-7 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-400/15 to-transparent" />
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-xl bg-zinc-100 dark:bg-zinc-1000/10 flex items-center justify-center shrink-0">
              <Scale className="w-4 h-4 text-zinc-800 dark:text-zinc-200" />
            </div>
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">Usage & Credits</h2>
          </div>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed mb-3">
            Access to FAINL is governed by usage tiers:
          </p>
          <ul className="space-y-2 text-sm text-zinc-500 dark:text-zinc-400">
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">Turns & Credits:</strong> Each complete consensus session (analysis → debate → verdict) consumes one Turn. Credits and Turns are non-refundable once consumed.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">BYO API Keys:</strong> If you provide your own API keys, you are responsible for any costs incurred at the provider level.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-1.5 shrink-0" />
              <span><strong className="text-zinc-700 dark:text-zinc-300">Fair Use:</strong> We reserve the right to throttle or suspend access for accounts showing bot-like or abusive usage patterns.</span>
            </li>
          </ul>
        </div>

        <div className="glass-card card-shadow rounded-2xl p-6 md:p-7 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-400/15 to-transparent" />
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-xl bg-red-50 dark:bg-red-500/10 flex items-center justify-center shrink-0">
              <AlertTriangle className="w-4 h-4 text-red-600 dark:text-red-400" />
            </div>
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">Prohibited Uses</h2>
          </div>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed mb-3">
            The following uses of FAINL are strictly prohibited:
          </p>
          <ul className="space-y-2 text-sm text-zinc-500 dark:text-zinc-400">
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
              <span>Generating malicious code, malware, or exploit instructions.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
              <span>Requesting instructions related to biological or chemical weapons.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
              <span>Automated harassment, spam, or large-scale disinformation campaigns.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
              <span>Any activity that violates applicable laws in your jurisdiction.</span>
            </li>
          </ul>
        </div>

        <div className="glass-card card-shadow rounded-2xl p-6 md:p-7 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-400/15 to-transparent" />
          <div className="flex items-center gap-3 mb-4">
            <div className="w-9 h-9 rounded-xl bg-zinc-100 dark:bg-zinc-1000/10 flex items-center justify-center shrink-0">
              <FileText className="w-4 h-4 text-zinc-800 dark:text-zinc-200" />
            </div>
            <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">Account Termination</h2>
          </div>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed">
            Violation of these terms may result in immediate suspension or permanent removal of your account. We reserve the right to revoke access for accounts that compromise the integrity of the service or violate these terms, at our sole discretion.
          </p>
        </div>
      </div>

      <p className="mt-8 text-center text-[11px] text-zinc-400 dark:text-zinc-600 font-medium">
        Questions about these terms?{' '}
        <span className="text-zinc-800 dark:text-zinc-200 font-semibold">Contact us via the Contact page.</span>
      </p>
    </div>
  );
};
